// <auto-generated />
using System;
using FoodInventoryApp.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodInventoryApp.Migrations
{
    [DbContext(typeof(FoodInventoryContext))]
    [Migration("20200201201702_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FoodInventoryApp.Database.InventoryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Expiration");

                    b.Property<string>("Item");

                    b.Property<float>("Qty");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("InventoryLines");
                });

            modelBuilder.Entity("FoodInventoryApp.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FoodInventoryApp.Database.UserInventoryMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InventoryLineId");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("InventoryLineId");

                    b.HasIndex("UserId");

                    b.ToTable("UserInventoryMappings");
                });

            modelBuilder.Entity("FoodInventoryApp.Database.UserInventoryMapping", b =>
                {
                    b.HasOne("FoodInventoryApp.Database.InventoryLine", "InventoryLine")
                        .WithMany()
                        .HasForeignKey("InventoryLineId");

                    b.HasOne("FoodInventoryApp.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
